import Head from 'next/head'
import Image from 'next/image';
import Link from 'next/link'
import styles from '../../styles/Home.module.scss'

export default function About() {
  return (
    <div>
      <div className={styles.container}>
        <Head>
          <title>Acquiring Technology</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            About <a href="https://nextjs.org">Acquiring Technology!</a>
          </h1>

          <Image src="/logo_without_text.webp" alt="Vercel Logo" width={45} height={45} />
        </main>

      </div>

      <div className='row'>
        <div className='col-md-12 border-top'>
          <div className="container  ">
            <footer className="d-flex flex-wrap justify-content-between align-items-center my-4">
              <div className="col-md-4 d-flex align-items-center">
                <Link href="/about" className="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                  <Image src="/logo_without_text.png" alt="Vercel Logo" width={45} height={45} />
                </Link>
                <span className="mb-3 mb-md-0 text-muted ms-2">© 2022 Acquiring Technology!</span>
              </div>

              {/* <ul className="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li className="ms-3"><a className="text-muted" href="#"><svg className="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
            <li className="ms-3"><a className="text-muted" href="#"><svg className="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
            <li className="ms-3"><a className="text-muted" href="#"><svg className="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
          </ul> */}
            </footer>
          </div>
        </div>
      </div>




    </div>
  )
}
